# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12test_message.proto\x12\x07pj.test\"}\n\x0bTestMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x11\n\tvalue_sin\x18\x02 \x01(\x01\x12\x11\n\tvalue_cos\x18\x03 \x01(\x01\x12\x0f\n\x07\x63ounter\x18\x04 \x01(\x05\x12$\n\x07sensors\x18\x05 \x01(\x0b\x32\x13.pj.test.SensorData\"E\n\nSensorData\x12\x13\n\x0btemperature\x18\x01 \x01(\x01\x12\x10\n\x08pressure\x18\x02 \x01(\x01\x12\x10\n\x08humidity\x18\x03 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTMESSAGE._serialized_start=31
  _TESTMESSAGE._serialized_end=156
  _SENSORDATA._serialized_start=158
  _SENSORDATA._serialized_end=227
# @@protoc_insertion_point(module_scope)
